main:
  train_episodes: 10000
  eval_episodes: 1
  games_path: '../sample_games'
  vocab_path: '../vocab.txt'
  pretrained_path: '../glove.6B.50d.txt'
  use_pretrained: False
  embedding_dim: 50
  environment_batch_size: 10
  update_frequency: 1
  use_adaptive_epsilon: True

agent:
  summary_dir: 'Summaries'
  gamma: 0.8
  training_batch_size: 10
  replay_memory_capacity: 50000
  replay_memory_priority_fraction: 0.25
  random_seed: 42
  epsilon_start: 1.
  epsilon_end: 0.1
  epsilon_annealing_interval: 900
  shuffle_actions: True
  batch_oneshot: True

model:
  clip_by_norm: 5.
  optimizer: 'default'
  learning_rate: 0.001
  states_network: [128, 32]
  actions_network: [32]
  softmax_scaling_factor: 0
  loss: 'default'
  state_encoder: 'default'
  rnn_cell: 'gru'
  keep_prob: 0.9
  share_embeddings: False
